global using Dapper;
global using Microsoft.Data.Sqlite;
global using System.Data;
using CarCareAPI.Brokers.Storages;
using CarCareAPI.Controllers;
using Scalar.AspNetCore;
using CarCareAPI.Services.Foundations;

var builder = WebApplication.CreateBuilder(args);
//builder.Services.AddOpenApi();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddTransient<IStorageBroker, StorageBroker>();
builder.Services.AddScoped<IRepairTypeService, RepairTypeService>();
builder.Services.AddScoped<IRepairService, RepairService>();
builder.Services.AddScoped<ICarClassService, CarClassService>();
builder.Services.AddScoped<ICarService, CarService>();
builder.Services.AddScoped<IArchivedRepairService, ArchivedRepairService>();
builder.Services.AddScoped<IGasService, GasService>();
builder.Services.AddScoped<IProfileService, ProfileService>();
builder.Services.AddScoped<IProfileCarService, ProfileCarService>();
builder.Services.AddScoped<IProfileRepairTypeService, ProfileRepairTypeService>();
var app = builder.Build();
//app.MapOpenApi();
app.MapScalarApiReference();
app.UseHttpsRedirection();
app.RegisterRoutes();
app.MapGet("/", () => Results.Redirect("/scalar/v1"));
app.Run();
